---
app:
  serviceType: NodePort
  image: fluentintegrations/flintx-product:1.0.0
  name: flintx-product
  version: 1.0.0
  namespace: flintx
  host: flintx-product.co
  port: 8086
  livenessProbe:
    failureThreshold: 3
    periodSeconds: 30
    timeoutSeconds: 10
    successThreshold: 1
    initialDelaySeconds: 30
    httpGet:
      path: /q/health/live
      scheme: HTTP
      port: 8086
  readinessProbe:
    failureThreshold: 3
    timeoutSeconds: 10
    periodSeconds: 45
    successThreshold: 1
    initialDelaySeconds: 45
    httpGet:
      path: /q/health/ready
      scheme: HTTP
      port: 8086