apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flintx-persitent-volume-claim
  namespace: {{ .Values.app.namespace }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi