kind: PersistentVolume
apiVersion: v1
metadata:
  name: flintx-persitent-volume
  namespace: {{ .Values.app.namespace }}
spec:
  storageClassName: standard
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/config"
